# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
webrick:
  headers:
    My-Header: ALL In - Angela Lynn Lindow
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
title: ALL In
email: angelalindow@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  These are the ramblings of Angela Lynn Lindow: wife, mom of 3, lover of
  startups, fiber arts fan, aspiring developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: allindow
github_username:  allindow

# Build settings
markdown: kramdown
timezone: America/Denver
encoding: utf-8
